baseurl = "https://ppaci.github.io/blog/"
title = "Pierre's blog"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Pierre PACI"
  info = "Cloud Engineer And Kubernetes specialist"
  description = "Pierre's personnal blog."
  keywords = "blog,developer,personal"
  avatarurl = "img/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = "Don't expect too much from here."
  hideFooter = false
  hideCredits = true
  hideCopyright = false
  since = 2021

  enableTwemoji = true

  colorScheme = "light"
  hidecolorschemetoggle = true

  customCSS = ["css/style.css"]
  customSCSS = []
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/PPACI/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/pierre_paci/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"